version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "jamf/opensource-regatta-write"

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "jamf/opensource-regatta-write"

